-- Lịch chiếu mẫu được tạo tương đối từ ngày chạy migration để luôn có dữ liệu sắp tới.
-- Các khung giờ trong cùng một phòng không chồng lấn nhau.
INSERT INTO showtimes (start_time, end_time, movie_id, room_id, deleted)
VALUES
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 10 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 742 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 1, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 14 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 948 MINUTE), (SELECT id FROM movies WHERE title = 'Thành Phố Sau Cơn Mưa'), 1, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 11 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 802 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 4, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 19 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 1282 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 6, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 20 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), INTERVAL 1342 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 8, FALSE),

    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 9 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 682 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 2, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 13 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 906 MINUTE), (SELECT id FROM movies WHERE title = 'Mật Mã Dưới Lòng Biển'), 2, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 16 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 1102 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 5, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 18 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 2 DAY), INTERVAL 1222 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 7, FALSE),

    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 10 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 708 MINUTE), (SELECT id FROM movies WHERE title = 'Thành Phố Sau Cơn Mưa'), 3, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 15 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 1042 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 3, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 19 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 1266 MINUTE), (SELECT id FROM movies WHERE title = 'Mật Mã Dưới Lòng Biển'), 4, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 20 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY), INTERVAL 1354 MINUTE), (SELECT id FROM movies WHERE title = 'Những Ngày Không Tên'), 6, FALSE),

    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 10 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 742 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 1, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 17 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 1162 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 4, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 20 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 4 DAY), INTERVAL 1348 MINUTE), (SELECT id FROM movies WHERE title = 'Thành Phố Sau Cơn Mưa'), 8, FALSE),

    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY), INTERVAL 13 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY), INTERVAL 922 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 2, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY), INTERVAL 18 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY), INTERVAL 1217 MINUTE), (SELECT id FROM movies WHERE title = 'Kẻ Canh Giữ Ký Ức'), 5, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 6 DAY), INTERVAL 11 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 6 DAY), INTERVAL 802 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 6, FALSE),
    (DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY), INTERVAL 20 HOUR), DATE_ADD(DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY), INTERVAL 1342 MINUTE), (SELECT id FROM movies WHERE title = 'Khoảng Trời Rực Rỡ'), 1, FALSE);
